version: "3"

services:
  shopping-app-django-postgres-db-dev:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DEV_DJANGO_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEV_DJANGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEV_DJANGO_DATABASE_NAME}
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DEV_DJANGO_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres-django-network
    restart: always

  shopping-app-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - postgres-django-network
    restart: always
    depends_on:
      shopping-app-django-postgres-db-dev:
        condition: service_healthy

networks:
  postgres-django-network:
    driver: bridge

volumes:
  dev-postgres-data:
    external: false
